{{- if .Values.lsdobserve.elastic.enabled -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: elastic-post-setup
spec:
  template:
    spec:
      initContainers:
      - args:
        - /bin/sh
        - -c
        - |
          set -x; while [ $(curl -u elastic:$ELASTIC_PASSWORD -skw '%{http_code}' "https://lsdobserve-es-http:9200" -o /dev/null) -ne 200 ]; do
            sleep 5;
          done
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: wait-for-elastic
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
      - args:
        - /bin/sh
        - -c
        - |
          set -x; while [ $(curl -u elastic:$ELASTIC_PASSWORD -skw '%{http_code}' "http://lsdobserve-kb-http:5601/api/spaces/space/default" -o /dev/null) -ne 200 ]; do
            sleep 5;
          done
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: wait-for-kibana
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
      containers:
      - args:
        - -c
        - "curl -sk -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdobserve-filebeat.ilm.policy.k8s.json \"https://lsdobserve-es-http:9200/_ilm/policy/filebeat-k8s\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: filebeat-ilm-policy-k8s
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files
      - args:
        - -c
        - "curl -sk -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdobserve-filebeat.ilm.policy.lsdo.json \"https://lsdobserve-es-http:9200/_ilm/policy/filebeat-lsdo\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: filebeat-ilm-policy-lsdo
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files
      - args:
        - -c
        - "curl -sk -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdobserve-filebeat.ilm.policy.project.json \"https://lsdobserve-es-http:9200/_ilm/policy/filebeat-project\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: filebeat-ilm-policy-project
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files
      - args:
        - -c
        - "curl -sk -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdobserve-filebeat.template.7.17.7.json \"https://lsdobserve-es-http:9200/_template/filebeat-7.17.7\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: filebeat-template
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files
      - args:
        - -c
        - "curl -sk -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdobserve-filebeat.template.k8s.json \"https://lsdobserve-es-http:9200/_template/filebeat-k8s\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: filebeat-template-k8s
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files
      - args:
        - -c
        - "curl -sk -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdobserve-filebeat.template.lsdo.json \"https://lsdobserve-es-http:9200/_template/filebeat-lsdo\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: filebeat-template-lsdo
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files
      - args:
        - -c
        - "curl -sk -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdobserve-filebeat.template.project.json \"https://lsdobserve-es-http:9200/_template/filebeat-project\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: filebeat-template-project
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files
      - args:
        - -c
        - "curl -sk -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdobserve-filebeat.bootstrap.k8s.json \"https://lsdobserve-es-http:9200/%3Cfilebeat-7.17.7-k8s-%7Bnow%2Fd%7D-000001%3E\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: filebeat-bootstrap-k8s
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files
      - args:
        - -c
        - "curl -sk -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdobserve-filebeat.bootstrap.lsdo.json \"https://lsdobserve-es-http:9200/%3Cfilebeat-7.17.7-lsdo-%7Bnow%2Fd%7D-000001%3E\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: filebeat-bootstrap-lsdo
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files
      - args:
        - -c
        - "curl -sk -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -X PUT -d @/opt/elastic/lsdobserve-filebeat.bootstrap.project.json \"https://lsdobserve-es-http:9200/%3Cfilebeat-7.17.7-project-all-%7Bnow%2Fd%7D-000001%3E\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: filebeat-bootstrap-project
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files
      - args:
        - -c
        - "curl -sk -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -H 'kbn-xsrf: true' -X POST -d @/opt/elastic/lsdobserve-filebeat.idxpattern.project.json \"http://lsdobserve-kb-http:5601/api/index_patterns/index_pattern\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: filebeat-idxpattern-project
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files
      - args:
        - -c
        - "curl -sk -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -H 'kbn-xsrf: true' -X POST -d @/opt/elastic/lsdobserve-filebeat.idxpattern.lsdo.json \"http://lsdobserve-kb-http:5601/api/index_patterns/index_pattern\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: filebeat-idxpattern-lsdo
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files
      - args:
        - -c
        - "curl -sk -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -H 'kbn-xsrf: true' -X POST -d @/opt/elastic/lsdobserve-filebeat.idxpattern.k8s.json \"http://lsdobserve-kb-http:5601/api/index_patterns/index_pattern\""
        command:
        - /bin/sh
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdobserve-es-elastic-user
                key: elastic
        image: {{ .Values.lsdobserve.curl.image }}
        name: filebeat-idxpattern-k8s
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /opt/elastic/
          name: elastic-filebeat-custom-files
      restartPolicy: Never
      volumes:
      - configMap:
          defaultMode: 420
          name: elastic-filebeat-custom-files
        name: elastic-filebeat-custom-files
---
{{- end }}
