# Grafana Dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-kubernetes-overview
data:
  grafana-dashboard-kubernetes-overview.json: |-
{{ .Files.Get "dashboards/lsdcontainer/grafana-dashboard-kubernetes-overview.json" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-namespace-details
data:
  grafana-dashboard-namespace-details.json: |-
{{ .Files.Get "dashboards/lsdcontainer/grafana-dashboard-namespace-details.json" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-node-namespace-details
data:
  grafana-dashboard-node-namespace-details.json: |-
{{ .Files.Get "dashboards/lsdcontainer/grafana-dashboard-node-namespace-details.json" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-rook-ceph-overview
data:
  rook-ceph-dashboard.json: |-
{{ .Files.Get "dashboards/lsdcontainer/grafana-dashboard-rook-ceph.json" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-exporter-for-prometheus-dashboard
data:
  node-exporter-for-prometheus-dashboard.json: |-
{{ .Files.Get "dashboards/lsdcontainer/grafana-dashboard-node-exporter.json" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: strimzi-cruise-control-dashboard
data:
  strimzi-cruise-control-dashboard.json: |-
{{ .Files.Get "dashboards/kafka/strimzi-cruise-control.json" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: strimzi-kafka-connect-dashboard
data:
  strimzi-kafka-connect-dashboard.json: |-
{{ .Files.Get "dashboards/kafka/strimzi-kafka-connect.json" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: strimzi-kafka-exporter-dashboard
data:
  strimzi-kafka-exporter-dashboard.json: |-
{{ .Files.Get "dashboards/kafka/strimzi-kafka-exporter.json" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: strimzi-kafka-dashboard
data:
  strimzi-kafka-dashboard.json: |-
{{ .Files.Get "dashboards/kafka/strimzi-kafka.json" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: strimzi-operators-dashboard
data:
  strimzi-operators-dashboard.json: |-
{{ .Files.Get "dashboards/kafka/strimzi-operators.json" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: strimzi-zookeeper-dashboard
data:
  strimzi-zookeeper-dashboard.json: |-
{{ .Files.Get "dashboards/kafka/strimzi-zookeeper.json" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssl-monitoring
data:
  SSL-Monotoring.json: |-
{{ .Files.Get "dashboards/sslmonitoring/SSL-Monitoring.json" | indent 4}}
